[
  {
    id: 1,
    idCategoria: "servicios",
    nombre: "Asesoría digital personalizada",
    precio: 20000,
    stock: 0,
    img: "",
  },
  {
    id: 2,
    idCategoria: "servicios",
    nombre: "Manejo de campañas publicitarias",
    precio: 30000,
    stock: 0,
    img: "",
  },
  {
    id: 3,
    idCategoria: "servicios",
    nombre: "Consultoría de publicidad digital",
    precio: 4000,
    stock: 0,
    img: "",
  },
  {
    id: 4,
    idCategoria: "cursos",
    nombre: "Kit creador",
    precio: 2800,
    stock: 0,
    img: "",
  },
  {
    id: 5,
    idCategoria: "cursos",
    nombre: "Kit diseño",
    precio: 1600,
    stock: 0,
    img: "",
  },
  {
    id: 6,
    idCategoria: "herramientas",
    nombre: "E-book Baúl Creativo",
    precio: 500,
    stock: 0,
    img: "",
  }
];
